### PR TITLE
Allow to configure Accept header treatment

### LINKED ISSUE #4: Required accept header
The `Accept` header is required to have a value of `application/vnd.api+json` while the spec states:

> Clients that include the JSON API media type in their Accept header MUST specify the media type there at least once without any media type parameters.

This means that the client should be able to make requests without the requirement of specifying an `Accept` value.

### PR DESCRIPTION
**Pull request by jelhan**
feat: support configuration of Accept header treatment
    
This commit changes default behavior. Set accept-header-policy to 'require' to have same handling of Accept header as before.

PR includes #18. If you like to merge them separately feel free to cherry-pick.

Closes #4

### CODE REVIEW

**Comment by bkuhl** [comment]
Thanks for submitting this PR.  This seems like a great addition.  @jlaswell Are you opinionated and/or do you want to review this?  Looks good to me.

**Comment by jlaswell** [comment]
I actually took a look at this earlier this morning and think it's a good idea for how to handle default behavior. Thanks for cleaning up the long standing issue, @jelhan! ^.^

Since this does affect default behavior, we should bump major version and dupe branches for a bit so we can backport any new features or fixes. :/ That'll require an update to the CHANGELOG, and then we should add a [suggest](https://getcomposer.org/doc/04-schema.md#suggest) to the composer.json to update the package to 2.x.x. I can handle those changes @jelhan, if you don't want to deal with those administrative tasks. I'd like to add it as part of this PR though, so that it all happens at the same point in time.

**Comment by jelhan** [comment]
@jlaswell I would appreciate if you handle these changes since I haven't much spare time these days. Also I'm not quite sure if there are any other changes which should be taken into account when updating changelog. Will merge a PR against my branch as soon as possible.

**Comment by jlaswell** [comment]
@jelhan 👍  It's a Friday, and I'm wrapping up some work myself, but I'll make a note to get to this and hopefully have it in sometime Monday.

**Comment by ahuininga** [comment]
Any progress on this?

**Comment by bkuhl** [comment]
@jlaswell ?

**Comment by jlaswell** [comment]
I say this is good to get a merge, but I do think that a major version bump will be required here unless we do a default value for that updated constructor.

**Comment by bkuhl** [comment]
With it being a smaller change, that's going to be resolved via IOC for most uses, would it make sense to bump to 1.4 instead of 2.0?

**Comment by jlaswell** [comment]
That's probably 100% of the use cases, since no one will be extending that guard. I'm fine with the 1.4 bump, I think the config call will event just return `''` which is an empty string, so it should be fine. 👍

**Comment by bkuhl** [comment]
Actually, I'm going to revert this back so the default configuration is `require` and not `default`, so the functionality remains consistent.

**Pull request merged**
